// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SignalFlow.Infrastructure.Data;

#nullable disable

namespace SignalFlow.Infrastructure.Migrations
{
    [DbContext(typeof(SignalFlowDbContext))]
    partial class SignalFlowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("SignalFlow.Domain.Entities.DecisionRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("AiOutputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("AuditHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("CompletionTokens")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DecisionReason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FinalDecision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("InputJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LatencyMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("PolicyPassed")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PromptTokens")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RenderedPrompt")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("RunType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SchemaErrorsJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("SchemaValid")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("TemplateVersionId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<int>("TotalTokens")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "CreatedAt");

                    b.ToTable("DecisionRuns");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.HumanOverride", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DecisionRunId")
                        .HasColumnType("TEXT");

                    b.Property<int>("NewDecision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OverriddenBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OverrideAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Reason")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionRunId")
                        .IsUnique();

                    b.ToTable("HumanOverrides");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PolicyEvaluation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("DecisionRunId")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetailsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("Passed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PolicyKey")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DecisionRunId");

                    b.ToTable("PolicyEvaluations");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PromptTemplate", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId", "Key")
                        .IsUnique();

                    b.ToTable("PromptTemplates");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PromptTemplateVersion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("InputSchemaJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("OutputSchemaJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PromptTemplateId")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Version")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PromptTemplateId", "Version")
                        .IsUnique();

                    b.ToTable("PromptTemplateVersions");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("ApiKeyHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Tenants");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.TenantConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<bool>("AllowHumanOverride")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DefaultModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("HardMaxDTI")
                        .HasColumnType("TEXT");

                    b.Property<int>("HardMinCreditScore")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxDelinquencies12m")
                        .HasColumnType("INTEGER");

                    b.Property<int>("MaxRequestedAmount")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("MinConfidence")
                        .HasColumnType("TEXT");

                    b.Property<bool>("RequireSchemaValid")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReviewCreditScoreBelow")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ReviewDTIAbove")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("TenantConfigs");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.HumanOverride", b =>
                {
                    b.HasOne("SignalFlow.Domain.Entities.DecisionRun", null)
                        .WithOne("HumanOverride")
                        .HasForeignKey("SignalFlow.Domain.Entities.HumanOverride", "DecisionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PolicyEvaluation", b =>
                {
                    b.HasOne("SignalFlow.Domain.Entities.DecisionRun", null)
                        .WithMany("PolicyEvaluations")
                        .HasForeignKey("DecisionRunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PromptTemplateVersion", b =>
                {
                    b.HasOne("SignalFlow.Domain.Entities.PromptTemplate", null)
                        .WithMany("Versions")
                        .HasForeignKey("PromptTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.TenantConfig", b =>
                {
                    b.HasOne("SignalFlow.Domain.Entities.Tenant", null)
                        .WithOne("Config")
                        .HasForeignKey("SignalFlow.Domain.Entities.TenantConfig", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.DecisionRun", b =>
                {
                    b.Navigation("HumanOverride");

                    b.Navigation("PolicyEvaluations");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.PromptTemplate", b =>
                {
                    b.Navigation("Versions");
                });

            modelBuilder.Entity("SignalFlow.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Config")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
